image: ubuntu-gce-c

environment:
  ANDROID_SDK_ROOT: /usr/lib/android-sdk
  NDK_VERSION: 25.2.9519653
  LEGACY_NDK_VERSION: 21.4.7075529
  LEGACY_NDK: $ANDROID_SDK_ROOT/ndk/$LEGACY_NDK_VERSION
  SDK_VERSION: android-33
  ANDROID_NDK_GFORTRAN_ARCHIVE_ARM64: gcc-arm64-linux-x86_64.tar.bz2
  ANDROID_NDK_GFORTRAN_ARCHIVE_ARM: gcc-arm-linux-x86_64.tar.bz2
  DIST_NAME: mydist
  DIST_PATH: /home/appveyor/.local/share/python-for-android/dists/$DIST_NAME

stack:
- python 3.12

install:
# update build version
- ps: |
    if ($env:APPVEYOR_REPO_TAG_NAME) {
      $v = $env:APPVEYOR_REPO_TAG_NAME.replace("v", "")
    } else {
      $cv = [version](git describe --abbrev=0).substring(1)
      $v = "$($cv.major).$($cv.minor+1).0+$($env:APPVEYOR_BUILD_NUMBER)"
    }
    Update-AppveyorBuild -Version $v

# install NDK
- echo "y" | sdkmanager --install "ndk;$NDK_VERSION" --channel=3 > /dev/null
- echo "y" | sdkmanager --install "ndk;$LEGACY_NDK_VERSION" --channel=3 > /dev/null
- echo "y" | sdkmanager --install "platforms;$SDK_VERSION" > /dev/null

# install Fortran compiler
- curl -LO https://github.com/mzakharo/android-gfortran/releases/download/r21e/$ANDROID_NDK_GFORTRAN_ARCHIVE_ARM64
- curl -LO https://github.com/mzakharo/android-gfortran/releases/download/r21e/$ANDROID_NDK_GFORTRAN_ARCHIVE_ARM
- mkdir -p $LEGACY_NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/
- tar -xf $ANDROID_NDK_GFORTRAN_ARCHIVE_ARM64 -C $LEGACY_NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/ --strip-components 1
- mkdir -p $LEGACY_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/
- tar -xf $ANDROID_NDK_GFORTRAN_ARCHIVE_ARM -C $LEGACY_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/ --strip-components 1

# install Kivy for Android
- pip3 install .
- pip3 install --upgrade cython
- p4a --help

build_script:
- mkdir out
#- p4a create --requirements python3 --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_SDK_ROOT/ndk/$NDK_VERSION --dist-name serious_python
- p4a create --requirements python3 --arch arm64-v8a --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_SDK_ROOT/ndk/$NDK_VERSION --dist-name $DIST_NAME
- ls -al $DIST_PATH
- python ci/zip_diff.py $DIST_PATH out/python-for-android-dist-$APPVEYOR_BUILD_VERSION.zip
- python ci/update_index.py out/android-dist.json dist $APPVEYOR_BUILD_VERSION

artifacts:
- path: out/*

test: off